name: Install workspace
description: Setup node and install project dependencies

inputs:
  NPM_TOKEN:
    required: false

runs:
  using: "composite"
  steps:
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache node dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Update .npmrc
      shell: bash
      run: |
        [ -z "${{ inputs.NPM_TOKEN }}" ] && echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" > .npmrc || echo "No npm token provided, skipping .npmrc update."

    - name: Install
      shell: bash
      run: yarn install --frozen-lockfile
      working-directory: ./
