name: setup-solana-local-validator
description: Install dependencies required to run solana local validator

inputs:
  SOLANA_VERSION:
    required: false
    default: v1.14.10
  ANCHOR_VERSION:
    required: false
    default: 0.24.2

runs:
  using: "composite"
  steps:
    - name: install rust
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      shell: bash

    - name: install cargo
      run: echo "/home/runner/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: install solana CLI and anchor
      uses: nick-fields/retry@v2
      # the installation fails intermittently, so retry up to 3 times
      with:
        timeout_minutes: 2
        max_attempts: 3
        command: |
          curl -sSfL https://release.solana.com/${{ inputs.SOLANA_VERSION }}/install | sh
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          npm i -g @project-serum/anchor-cli@${{ inputs.ANCHOR_VERSION }} ts-mocha typescript