name: Build, lint and test

# on pull request or merge to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test and lint civic-link on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare workspace
        uses: ./.github/workflows/actions/workspace-install
      - name: Lint
        run: yarn lint
      - name: Build
        working-directory: ./
        run: yarn build
      - name: Test
        run: yarn test
