name: Publish civic-link

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  test:
    name: Test and lint civic-link on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup solana-local-validator
        uses: ./.github/workflows/actions/solana-local-validator

      - name: Prepare workspace
        uses: ./.github/workflows/actions/workspace-install
        with:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISHING_TOKEN }}

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish
        run: |
          echo "Publishing @civic/civic-link v${{ github.ref_name }}";
          NODE_ENV=production yarn publish --access public ---new-version ${{ github.ref_name }};
